local STRINGS = GLOBAL.STRINGS
local CHARACTERS = GLOBAL.STRINGS.CHARACTERS

-- mound_structure description
CHARACTERS.GENERIC.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.GENERIC.DESCRIBE.MOUND
CHARACTERS.WILLOW.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WILLOW.DESCRIBE.MOUND
CHARACTERS.WOLFGANG.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WOLFGANG.DESCRIBE.MOUND
CHARACTERS.WX78.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WX78.DESCRIBE.MOUND
CHARACTERS.WICKERBOTTOM.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WICKERBOTTOM.DESCRIBE.MOUND
CHARACTERS.WOODIE.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WOODIE.DESCRIBE.MOUND
CHARACTERS.WAXWELL.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WAXWELL.DESCRIBE.MOUND
CHARACTERS.WATHGRITHR.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WATHGRITHR.DESCRIBE.MOUND
CHARACTERS.WEBBER.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WEBBER.DESCRIBE.MOUND
CHARACTERS.WARLY.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WARLY.DESCRIBE.MOUND
CHARACTERS.WORMWOOD.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WORMWOOD.DESCRIBE.MOUND
CHARACTERS.WINONA.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WINONA.DESCRIBE.MOUND
CHARACTERS.WORTOX.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WORTOX.DESCRIBE.MOUND
CHARACTERS.WURT.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WURT.DESCRIBE.MOUND
CHARACTERS.WALTER.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WALTER.DESCRIBE.MOUND
CHARACTERS.WANDA.DESCRIBE.MOUND_STRUCTURE = CHARACTERS.WANDA.DESCRIBE.MOUND

-- new elixir descriptions for non-Wendy characters
for _, ELIXIR in ipairs(NEW_ELIXIRS) do
    CHARACTERS.GENERIC.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.GENERIC.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WILLOW.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WILLOW.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WOLFGANG.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WOLFGANG.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WX78.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WX78.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WICKERBOTTOM.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WICKERBOTTOM.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WOODIE.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WOODIE.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WAXWELL.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WAXWELL.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WATHGRITHR.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WATHGRITHR.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WEBBER.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WEBBER.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WARLY.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WARLY.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WORMWOOD.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WORMWOOD.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WINONA.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WINONA.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WORTOX.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WORTOX.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WURT.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WURT.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WALTER.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WALTER.DESCRIBE.GHOSTLYELIXIR_SPEED
    CHARACTERS.WANDA.DESCRIBE["NEWELIXIR_"..string.upper(ELIXIR)] = CHARACTERS.WANDA.DESCRIBE.GHOSTLYELIXIR_SPEED
end

-- Item names, recipe descriptions, and Wendy inspect dialogue
CHARACTERS.WENDY.ACTIONFAIL.GIVE.WRONG_ELIXIR = "I can't apply it without cleansing her!"
CHARACTERS.WENDY.ACTIONFAIL.GIVE.NO_ELIXIR = "It won't stick!"
CHARACTERS.WENDY.ACTIONFAIL.MOONOFFERING = {
    NO_FULLMOON = "I will have to wait for a full moon.",
    NO_NIGHT = "I will have to wait for night.",
    GLASSED = "There is no water for an offering.",
}

CHARACTERS.WENDY.DESCRIBE.ABIGAIL.NIGHTMARE = "A-...Abigail...?"
CHARACTERS.WENDY.DESCRIBE.MOONDIAL.RITUAL_STARTED = "I can see shapes in the water."
CHARACTERS.WENDY.DESCRIBE.MOONDIAL.RITUAL_COMPLETE = "Abigail? Abigail!"

STRINGS.NAMES.GRAVESTONE_STRUCTURE = "Headstone"
STRINGS.RECIPE_DESC.GRAVESTONE_STRUCTURE = "Revenant relocation."
CHARACTERS.WENDY.DESCRIBE.GRAVESTONE_STRUCTURE = "Asylum for a lost soul."

STRINGS.NAMES.MOUND_STRUCTURE = "Grave"
CHARACTERS.WENDY.DESCRIBE.MOUND_STRUCTURE = {
    GENERIC = "Now we can help.",
    DUG = "All it needs is an offering."
}

STRINGS.NAMES.NEWELIXIR_SANITYAURA = "Floral Incense"
STRINGS.RECIPE_DESC.NEWELIXIR_SANITYAURA = "Spirit-scents."
CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_SANITYAURA = "It smells of hyacinth and lily."

STRINGS.NAMES.NEWELIXIR_LIGHTAURA = "Radiant Remedy"
STRINGS.RECIPE_DESC.NEWELIXIR_LIGHTAURA = "A brilliant blazing brew."
CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_LIGHTAURA = "Abigail would love this one."

STRINGS.NAMES.NEWELIXIR_HEALTHDAMAGE = "Sanguine Solution"
STRINGS.RECIPE_DESC.NEWELIXIR_HEALTHDAMAGE = "Harness the power of your grevious wounds."
CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_HEALTHDAMAGE = "The closer we get, the stronger we become."

STRINGS.NAMES.NEWELIXIR_CLEANSE = "Purifying Balm"
STRINGS.RECIPE_DESC.NEWELIXIR_CLEANSE = "Cleanse your sister's soul."
CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_CLEANSE = "This will help you stay calm."

STRINGS.NAMES.NEWELIXIR_INSANITYDAMAGE = "Nightmare Serum"
STRINGS.RECIPE_DESC.NEWELIXIR_INSANITYDAMAGE = "Harness the power of your bad dreams."
CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_INSANITYDAMAGE = "Oh, but it wasn't a dream."

STRINGS.NAMES.NEWELIXIR_SHADOWFIGHTER = "Tenebrous Tincture"
STRINGS.RECIPE_DESC.NEWELIXIR_SHADOWFIGHTER = "Cloak your spirit in the shadows."
CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_SHADOWFIGHTER = "This will help you see them too."

STRINGS.NAMES.NEWELIXIR_LIGHTNING = "Distilled Wrath"
STRINGS.RECIPE_DESC.NEWELIXIR_LIGHTNING = "Smite with the fury of the dead."
CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_LIGHTNING = "It tingles."

--STRINGS.NAMES.NEWELIXIR_ = "item_name"
--STRINGS.RECIPE_DESC.NEWELIXIR_ = "recipe_description"
--CHARACTERS.WENDY.DESCRIBE.NEWELIXIR_ = "inspect_dialogue"